---
- name: copy file 
  hosts: dev
  become: true
  tasks:
  - name: copy war file
    copy:
      src: /root/.jenkins/workspace/mvn/webapp/target/webapp.war
      dest: /media/apache-tomcat-10.0.12/webapps
      remote_dest: yes
